// Generated by Wrangler on Wed Aug 28 2024 12:33:15 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	R2_BUCKET: R2Bucket;
	DB: D1Database;
	VECTORIZE_INDEX: VectorizeIndex;
	AI: Ai;
}
