// Generated by Wrangler on Mon Aug 26 2024 14:18:37 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	MY_VARIABLE: "server!!!";
	R2_BUCKET: R2Bucket;
	VECTORIZE_INDEX: VectorizeIndex;
	AI: unknown;
}
