// Generated by Wrangler on Fri Aug 30 2024 14:49:51 GMT+0200 (GMT+02:00)
// by running `wrangler types`

interface Env {
	rate_limiter: KVNamespace;
	GROQ_API_KEY: string;
	OPENAI_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	R2_BUCKET: R2Bucket;
	DB: D1Database;
	VECTORIZE_INDEX: VectorizeIndex;
	AI: Ai;
}
